name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          maven-version: '3.9.6'
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: "C:\\QA automation\\apache-maven-3.9.6\\bin\\mvn" -v

      - name: Run Selenium Tests
        run: |
          "C:\\QA automation\\apache-maven-3.9.6\\bin\\mvn" surefire:test

      - name: Check Java version
        run: java -version

      - name: Check Maven version
        run: "C:\\QA automation\\apache-maven-3.9.6\\bin\\mvn" -v
