name: Automated Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up ChromeDriver
        run: |
          wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE > LATEST_RELEASE
          export CHROME_VERSION=$(cat LATEST_RELEASE)
          wget -q https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver || (echo "Failed to install ChromeDriver" && exit 1)

      - name: Set up EdgeDriver
        run: |
          wget -q https://msedgedriver.azureedge.net/123.0.2420.97/edgedriver_linux64.zip
          unzip -q edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/msedgedriver
          sudo chmod +x /usr/local/bin/msedgedriver || (echo "Failed to install EdgeDriver" && exit 1)

      - name: Run tests
        run: mvn test
        env:
          PLATFORM_AND_BROWSER: 'EdgeDriver'

      # Archive test results (Allure results)
      - name: Archive Allure results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results/

      # Install Allure
      - name: Install Allure
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure -y

      # Generate Allure report
      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      # Publish Allure report to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TESTKEYCICD }}
          publish_dir: ./allure-report
